"""
scripts/decision_action_agent/tools.py

Tools for the Decision & Action Agent (Agent 3 of the pipeline).

Three tools:
  1. notify_manager         — Gmail email to the manager about rep performance + recommended actions
  2. message_rep            — Gmail email to the rep with a brief of key findings
  3. create_salesforce_task — Salesforce Task anchored to an Account, for the
                               expansion-whitespace nudge (Rule 3) — calls our
                               own GCP-hosted salesforce_mcp_server

rep_email and manager_email are pulled from session state — never invented by the model.
"""

import base64
from email.mime.text import MIMEText

from google.adk.tools import FunctionTool, ToolContext

from auth.auth import build_gmail_service
from scripts.salesforce_mcp_client import call_salesforce_mcp_tool


def _build_mime_email(to: str, subject: str, body_html: str) -> str:
    """Encode a MIME HTML email as a base64url string for the Gmail API."""
    msg = MIMEText(body_html, "html")
    msg["to"] = to
    msg["subject"] = subject
    return base64.urlsafe_b64encode(msg.as_bytes()).decode()


# ---------------------------------------------------------------------
# TOOL 1 — Notify manager (Gmail API)
# ---------------------------------------------------------------------

async def notify_manager(
    rep_id: str,
    rep_name: str,
    manager_email: str,
    performance_summary: str,
    recommended_actions: str,
    tool_context: ToolContext,
) -> dict:
    """Send a performance briefing email to the manager about this rep.

    Covers: overall attainment trajectory, critical deals, pipeline risks,
    and concrete recommended manager actions to move the needle.

    manager_email MUST come from session state — never invented or guessed.
    """
    subject = f"Rep Performance Alert — {rep_name} ({rep_id})"

    body_html = f"""
    <html><body style="font-family: Arial, sans-serif; line-height: 1.6;">
    <h2 style="color: #c0392b;">Rep Performance Briefing: {rep_name}</h2>
    <p><b>Rep ID:</b> {rep_id}</p>

    <h3>Performance Summary</h3>
    <p>{performance_summary.replace(chr(10), "<br>")}</p>

    <h3>Recommended Actions</h3>
    <p>{recommended_actions.replace(chr(10), "<br>")}</p>

    <hr>
    <p style="color: #7f8c8d; font-size: 12px;">
      Generated by the Sales Conversion Agent pipeline.
      Data sourced from Salesforce and Gong.
    </p>
    </body></html>
    """

    try:
        service = build_gmail_service()
        raw = _build_mime_email(manager_email, subject, body_html)
        sent = service.users().messages().send(userId="me", body={"raw": raw}).execute()

        return {
            "status": "SENT",
            "type": "notify_manager",
            "rep_id": rep_id,
            "rep_name": rep_name,
            "manager_email": manager_email,
            "subject": subject,
            "message_id": sent.get("id"),
        }

    except Exception as e:
        return {
            "status": "ERROR",
            "type": "notify_manager",
            "rep_id": rep_id,
            "rep_name": rep_name,
            "error_message": str(e),
        }


# ---------------------------------------------------------------------
# TOOL 2 — Message rep (Gmail API)
# ---------------------------------------------------------------------

async def message_rep(
    rep_id: str,
    rep_name: str,
    rep_email: str,
    findings_summary: str,
    tool_context: ToolContext,
) -> dict:
    """Send a brief findings email directly to the rep.

    Covers: key risks flagged across their pipeline, missed commitments,
    and the top actions they should take this week.

    rep_email MUST come from session state — never invented or guessed.
    """
    subject = f"Your Pipeline — Key Actions This Week"

    body_html = f"""
    <html><body style="font-family: Arial, sans-serif; line-height: 1.6;">
    <p>Hi {rep_name},</p>

    <p>Here's a brief summary of key findings across your pipeline
    that need your attention:</p>

    <div style="background: #f9f9f9; border-left: 4px solid #2980b9; padding: 12px 16px; margin: 16px 0;">
      {findings_summary.replace(chr(10), "<br>")}
    </div>

    <p>Please action these this week to keep your deals on track.</p>

    <p>Best,<br>Sales Ops</p>

    <hr>
    <p style="color: #7f8c8d; font-size: 12px;">
      Generated by the Sales Conversion Agent pipeline.
    </p>
    </body></html>
    """

    try:
        service = build_gmail_service()
        raw = _build_mime_email(rep_email, subject, body_html)
        sent = service.users().messages().send(userId="me", body={"raw": raw}).execute()

        return {
            "status": "SENT",
            "type": "message_rep",
            "rep_id": rep_id,
            "rep_name": rep_name,
            "rep_email": rep_email,
            "subject": subject,
            "message_id": sent.get("id"),
        }

    except Exception as e:
        return {
            "status": "ERROR",
            "type": "message_rep",
            "rep_id": rep_id,
            "rep_name": rep_name,
            "error_message": str(e),
        }


# ---------------------------------------------------------------------
# TOOL 3 — Create Salesforce task (Rule 3 — expansion-whitespace nudge)
# ---------------------------------------------------------------------

async def create_salesforce_task(
    rep_id: str,
    account_id: str,
    account_name: str,
    subject: str,
    description: str,
    tool_context: ToolContext,
) -> dict:
    """Create a Salesforce Task for the expansion-whitespace signal
    (account_analysis_agent's expansion_signal) — anchored to the Account
    (WhatId), assigned to the rep (OwnerId = rep_id, which is already a
    real Salesforce User ID — see data_collection_custom_agent).

    Calls the create_task tool on our own salesforce_mcp_server.
    """
    try:
        result = await call_salesforce_mcp_tool(
            "create_task",
            {
                "account_id": account_id,
                "owner_id": rep_id,
                "subject": subject,
                "description": description,
            },
        )
        return {
            "status": "SENT",
            "type": "create_salesforce_task",
            "rep_id": rep_id,
            "account_id": account_id,
            "account_name": account_name,
            "subject": subject,
            "task_id": result.get("id"),
        }
    except Exception as e:
        return {
            "status": "ERROR",
            "type": "create_salesforce_task",
            "rep_id": rep_id,
            "account_id": account_id,
            "account_name": account_name,
            "error_message": str(e),
        }


# ---------------------------------------------------------------------
# FunctionTool wrappers
# ---------------------------------------------------------------------

notify_manager_tool = FunctionTool(func=notify_manager)
message_rep_tool = FunctionTool(func=message_rep)
create_salesforce_task_tool = FunctionTool(func=create_salesforce_task)
